apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: ha
spec:
  containers:
  - name: curl-container
    image: curlimages/curl:latest
    command: ["sleep", "infinity"]
  restartPolicy: Always
